"""Game model.

Revision ID: 38c83f346136
Revises: e6eff1fe3eee
Create Date: 2022-07-21 14:17:40.856560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c83f346136'
down_revision = 'e6eff1fe3eee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('num_rounds', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('ix_games_winner_id'), 'games', ['winner_id'], unique=False)
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moves_id'), 'moves', ['id'], unique=False)
    op.create_table('players',
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.UniqueConstraint('game_id', 'user_id', name='unique_players')
    )
    op.create_index(op.f('ix_players_game_id'), 'players', ['game_id'], unique=False)
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rounds_game_id'), 'rounds', ['game_id'], unique=False)
    op.create_index(op.f('ix_rounds_id'), 'rounds', ['id'], unique=False)
    op.create_index(op.f('ix_rounds_winner_id'), 'rounds', ['winner_id'], unique=False)
    op.create_table('round_moves',
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('move_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.UniqueConstraint('round_id', 'move_id', name='unique_round_moves')
    )
    op.create_index(op.f('ix_round_moves_round_id'), 'round_moves', ['round_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_round_moves_round_id'), table_name='round_moves')
    op.drop_table('round_moves')
    op.drop_index(op.f('ix_rounds_winner_id'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_id'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_game_id'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_index(op.f('ix_players_game_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_moves_id'), table_name='moves')
    op.drop_table('moves')
    op.drop_index(op.f('ix_games_winner_id'), table_name='games')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
