"""Game model.

Revision ID: 63746f8ed7cc
Revises: e6eff1fe3eee
Create Date: 2022-07-20 11:28:48.071653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63746f8ed7cc'
down_revision = 'e6eff1fe3eee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_table('players',
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.UniqueConstraint('game_id', 'user_id', name='unique_players')
    )
    op.create_index(op.f('ix_players_game_id'), 'players', ['game_id'], unique=False)
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['winner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rounds_id'), 'rounds', ['id'], unique=False)
    op.create_index(op.f('ix_rounds_winner'), 'rounds', ['winner'], unique=False)
    op.create_table('round_options',
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.UniqueConstraint('round_id', 'user_id', 'option_id', name='unique_round_options')
    )
    op.create_index(op.f('ix_round_options_round_id'), 'round_options', ['round_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_round_options_round_id'), table_name='round_options')
    op.drop_table('round_options')
    op.drop_index(op.f('ix_rounds_winner'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_id'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_index(op.f('ix_players_game_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
