"""Added options table

Revision ID: 9c8d289ffb36
Revises: 0994cbd196d9
Create Date: 2022-07-19 22:44:03.624275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8d289ffb36'
down_revision = '0994cbd196d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_options_id'), 'options', ['id'], unique=False)
    op.create_index(op.f('ix_options_title'), 'options', ['title'], unique=True)
    op.create_table('beats',
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.Column('beat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beat_id'], ['options.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
    sa.UniqueConstraint('option_id', 'beat_id', name='unique_beats')
    )
    op.create_index(op.f('ix_beats_option_id'), 'beats', ['option_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beats_option_id'), table_name='beats')
    op.drop_table('beats')
    op.drop_index(op.f('ix_options_title'), table_name='options')
    op.drop_index(op.f('ix_options_id'), table_name='options')
    op.drop_table('options')
    # ### end Alembic commands ###
